name: Lint
on:
  push:
    paths:
      - "**.go"
      - go.mod
      - go.sum
  pull_request:
    paths:
      - "**.go"
      - go.mod
      - go.sum

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Check out code
        uses: actions/checkout@v3

      - name: Restore Go modules cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: go-${{ runner.os }}-${{ hashFiles('go.mod') }}
          restore-keys: |
            go-${{ runner.os }}-

      - name: Verify dependencies
        run: |
          go mod verify
          go mod download

          LINT_VERSION=1.50.1
          curl -fsSL https://github.com/golangci/golangci-lint/releases/download/v${LINT_VERSION}/golangci-lint-${LINT_VERSION}-linux-amd64.tar.gz | \
            tar xz --strip-components 1 --wildcards \*/golangci-lint
          mkdir -p bin && mv golangci-lint bin/

      - name: Run checks
        run: |
          STATUS=0
          assert-nothing-changed() {
            local diff
            "$@" >/dev/null || return 1
            if ! diff="$(git diff -U1 --color --exit-code)"; then
              printf '\e[31mError: running `\e[1m%s\e[22m` results in modifications that you must check into version control:\e[0m\n%s\n\n' "$*" "$diff" >&2
              git checkout -- .
              STATUS=1
            fi
          }

          assert-nothing-changed go fmt ./...
          assert-nothing-changed go mod tidy

          bin/golangci-lint run --out-format=github-actions --timeout=3m || STATUS=$?

          - name: Upload a Build Artifact

  uses: actions/upload-artifact@v3.1.2

  with:

    # Artifact name

    name: # optional, default is artifact

    # A file, directory or wildcard pattern that describes what to upload

    path: 

    # The desired behavior if no files are found using the provided path.

Available Options:

  warn: Output a warning but do not fail the action

  error: Fail the action with an error message

  ignore: Do not output any warnings or errors, the action does not fail

    if-no-files-found: # optional, default is warn

    # Duration after which artifact will expire in days. 0 means using default retention.

Minimum 1 day. Maximum 90 days unless changed from the repository settings page.

    retention-days: # optional
